# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testWKWebView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testWKWebView

  pod 'SSZipArchive'
  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  
end
